import React, { createContext, useContext } from 'react';
import { useSelector, useDispatch } from 'react-redux';
import { setLanguage as setLanguageAction } from '../store/slices/uiSlice';

const translations = {
  en: {
    // Navigation
    dashboard: 'Dashboard',
    orders: 'Orders',
    products: 'Products',
    customers: 'Customers',
    settings: 'Settings',
    companies: 'Brands',
    categories: 'Categories',
    packs: 'Packs',

    // Dashboard
    "Orders & Deliveries" : 'Orders & Deliveries',
    "Today's Revenue": "Today's Revenue",
    'Stock Alerts': 'Stock Alerts',
    Stock: 'Stock',
    totalProducts: 'Total Products',
    lowStock: 'Low Stock Items',
    'Total / Delivered': 'Total / Delivered',
    'Low / Out of Stock': 'Low / Out of Stock',
    expiringProducts: 'Expiring Soon',
    recentSales: 'Recent Sales',
    topProducts: 'Top Products',
    inventoryValue: 'Inventory Value',
    monthlyGrowth: 'Monthly Growth',
    dashboardTitle: 'Dashboard',
    dashboardWelcome: 'Welcome back! Here is your sales overview.',
    lastUpdated: 'Last Updated',
    refreshData: 'Refresh Data',
    topSellingProducts: 'Top Selling Products',
    bestPerformingItems: 'Best performing items by revenue',
    viewAll: 'View All',
    unknownProduct: 'Unknown Product',
    unitsSold: 'units sold',
    each: 'each',
    totalRevenue: 'Total Revenue',
    categorySales: 'Category Sales',
    revenueByProductCategory: 'Revenue by category',
    all: 'All Time',
    today: 'Today',
    month: 'Month',
    year: 'Year',
    ofTotalRevenue: 'of total revenue',
    noSalesData: 'No sales data available',
    salesWillAppearHere: 'Sales will appear here',
    noCategorySales: 'No category sales data',
    salesWillAppear: 'Sales will appear here',
    orderStatusSummary: 'Order Status Summary',
    overviewOrders: 'Overview of all orders',
    pendingOrders: 'Pending Orders',
    deliveredOrders: 'Delivered Orders',
    returnedOrders: 'Returned Orders',
    canceledOrders: 'Canceled Orders',
    pendingOrdersDesc: 'Orders waiting to be processed',
    deliveredOrdersDesc: 'Successfully delivered orders',
    returnedOrdersDesc: 'Orders that were returned',
    canceledOrdersDesc: 'Orders that were canceled',
    
    // Products
    'Total Products': 'Total Products',
    Product: 'Product',
    Category: 'Category',
    price: 'Price',
    'Current Stock': 'Current Stock',
    Offer: 'Offer',
    Status: 'Status',
    addProduct: 'Add Product',
    Actions: 'Actions',
    deleteProduct: 'Delete Product',
    searchProductsByName: 'Search products by name.',
    'Low Stock': 'Low Stock',
    'Out Of Stock': 'Out Of Stock',
    'All Categories': 'All Categories',
    Refresh: 'Refresh',
    'Product Management':'Product Management',
    'Monitor and manage your products': 'Monitor and manage your products',
    "Create Offer for": "Create Offer for",
    "Regular Price": "Regular Price",
    "Offer Price": "Offer Price",
    "Enter offer price": "Enter offer price",
    "Start Date": "Start Date",
    "End Date": "End Date",
    "Cancel": "Cancel",
    "Create Offer": "Create Offer",
    "Creating...": "Creating...",
    currency: "MAD",
    productName:'Product Name',
    enterProductName: 'Enter product name',
    selectCategory: 'Select Category',
    selectCompany: 'Select Company',
    productImage: 'Product Image',
    uploadImage: 'Upload Image',
    supportedFormats: 'Supported formats: JPG, PNG, GIF. Max size: 5MB',
    description: 'Description',
    enterProductDescription: 'Enter product description',
    editProduct:'Update Product',
    updateProductInfo: 'Update product information',
    addNewProduct: 'Add a new product',
    somethingWentWrong: 'Something went wrong. Please try again.',
    networkError: 'Network error. Please check your connection and try again.',
    selectImageFile: 'Please select an image file',
    imageSizeLimit: 'Image size must be less than 5MB',

    // Packs
    "Pack Management": "Pack Management",
    "Create and manage product packs": "Create and manage product packs",
    "New Pack": "New Pack",
    "Search packs by name...": "Search packs by name...",
    "Pack Name": "Pack Name",
    "No description": "No description",
    "No packs found": "No packs found",
    "Create your first pack to get started": "Create your first pack to get started",
    "packDetails": "Pack Details",
    "productDetails": "Product Details",
    "noDescription": "No description",
    "productsInPack": "Products in this pack",
    "noProductsInPack": "No products in this pack",
    "packSummary": "Pack Summary",
    "packPrice": "Pack Price",
    "created": "Created",
    "lastUpdated": "Last Updated",
    "create pack": "Create New Pack",

    nameRequired: "Pack name is required",
  nameMin: "Pack name must be at least 2 characters",
  nameMax: "Pack name cannot exceed 100 characters",

  descriptionRequired: "Description is required",
  descriptionMax: "Description cannot exceed 500 characters",

  priceRequired: "Price is required",
  priceInvalid: "Price must be a positive number",
  priceMax: "Price cannot exceed 10,000",

  productRequired: "Please select at least one product",

    // Categories
    skincare: 'Skincare',
    haircare: 'Hair Care',
    supplements: 'Supplements',
    babycare: 'Baby & Maternity',
    hygiene: 'Personal Hygiene',
    herbal: 'Herbal Remedies',
    cosmetics: 'Cosmetics',
    medical: 'Medical Devices',

    allTime: 'All Time',
    today: 'Today',
    week: 'This Week',
    month: 'This Month',

    // Orders
    'Orders Management': 'Orders Management',
    'Manage and track all customer orders': 'Manage and track all customer orders',
    'Total Orders': 'Total Orders',
    'Pending Orders': 'Pending Orders',
    'Delivered Orders': 'Delivered Orders',
    'Returned Orders': 'Returned Orders',
    'Cancelled Orders': 'Cancelled Orders',
    'Order Number': 'Order Number',
    'Customer': 'Customer',
    'Customer Name': 'Customer Name',
    'Items': 'Items',
    'Total': 'Total',
    'Order Status': 'Order Status',
    'Order Date': 'Order Date',
    'No orders found': 'No orders found',
    'Search orders by order number, name, or phone...': 'Search orders by order number, name, or phone...',
    'All Statuses': 'All Statuses',
    'All Dates': 'All Dates',
    'This Week': 'This Week',
    'This Month': 'This Month',
    'Previous': 'Previous',
    'Next': 'Next',
    'Showing': 'Showing',
    'per page': 'per page',
    'vs last month': 'vs last month',
    'Customer Information': 'Customer Information',
    'Order Information': 'Order Information',
    'Total Amount': 'Total Amount',
    'Order Items': 'Order Items',
    'Quantity': 'Quantity',

    // Companies
    Company: 'Company',
    somethingWentWrong : 'Something went wrong. Please try again.',
    networkError: 'Network error. Please check your connection and try again.',

     editPack: "Edit Pack",
  createPack: "Create Pack",
  page: "Page",
  of: "of",
  searchProductsByName: "Search products by name",
  previous: "Previous",
  next: "Next",
  showing: "Showing",
  to: "to",
  products: "products",
  packDetails: "Pack Details",
  packName: "Pack Name",
  description: "Description",
  characters: "characters",
  price: "Price",
  selectedProducts: "Selected Products",
  noProductsSelected: "No products selected",
  cancel: "Cancel",
  updating: "Updating...",
  creating: "Creating...",
  updatePack: "Update Pack",
  createPackBtn: "Create Pack",
  stock: "Stock",
  'searchProducts' : 'search Products ...',

   "loadingCategories": "Loading categories...",
  "errorLoadingCategories": "Error loading categories.",
  "categories": "Categories",
  "manageCategories": "Manage and organize your product categories",
  "refresh": "Refresh",
  "addCategory": "Add Category",
  "searchCategoriesPlaceholder": "Search categories by name...",
  "categoryList": "Category List",
  "name": "Name",
  "actions": "Actions",
  "edit": "Edit",
  "delete": "Delete",
  "noCategoriesFound": "No categories found",
  "tryAdjustingSearch": "Try adjusting your search",
  "showing": "Showing",
  "to": "to",
  "of": "of",
  "page": "Page",
  "previous": "Previous",
  "next": "Next",

   catNameRequired: "Category name is required",
    catNameMin: "Category name must be at least 2 characters long",
    catEditTitle: "Edit Category",
    catAddTitle: "Add New Category",
    catEditSubtitle: "Update category information",
    catAddSubtitle: "Create a new product category",
    catNameLabel: "Category Name",
    catNamePlaceholder: "Enter the category name",
    catUpdating: "Updating...",
    catCreating: "Creating...",
    catUpdateButton: "Update Category",
    catCreateButton: "Create Category",

    comTitle: "Companies Management",
    comAddButton: "Add Company",
    comTotalCompanies: "Total Companies",
    comSearchPlaceholder: "Search companies...",
    comName: "Name",
    comCreatedAt: "Created At",
    comActions: "Actions",
    comEdit: "Edit",
    comDelete: "Delete",
    comNoCompaniesFound: "No brands found",
    comTryAdjustingSearch: "Try adjusting your search criteria",
       comAddTitle: "Add New Brand",
   comAddDesc: "Create a new brand",
   comEditTitle: "Edit Brand",
   comEditDesc: "Update brand information",
   comNameLabel: "Brand Name",
   comNamePlaceholder: "Enter brand name",
   comNameRequired: "Brand name is required",
   comNameMinLength: "Brand name must be at least 2 characters long",
   comCreateButton: "Create Brand",
   comUpdateButton: "Update Brand",
   comCreating: "Creating...",
   comUpdating: "Updating...",

    // Common
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    view: 'View',
    add: 'Add',
    search: 'Search',
    filter: 'Filter',
    cusSearchPlaceholder : 'Search customers by name, email, phone, or location...',
    registeredCUs : 'Registered Customers',
    cusDirectory: 'Customer Directory',
    allregCus : 'All Registered Customers',
    cus : 'Customer',
    contact : 'Contact',
    orders : 'Orders',
    totalSpent : 'Total Spent',
    joined : 'joined',
    noCustomersFound: 'No customers found',
    cusDetails : 'Customer Details',
    personalInfo: 'Personal Information',
    customerSince: 'Customer Since',
    orderInfo : 'Order Information',
    totalOrders: 'Total Orders',
    averageSpent: 'Average Spent',
    lastOrder: 'Last Order',
    sendMail: 'Send Email',
    adminPanel: 'Admin Panel',
    managementDashboard: 'Management Dashboard',
    currentPassReq: 'Current password is required',
    newPassReq: 'New password is required',
    newPassMin: 'New password must be at least 6 characters long',
    newPassConfirm: 'Please confirm your new password',
    newPassMismatch: 'Passwords do not match',
    profileNotFound: 'Profile not found',
    profileNotFoundDesc: 'We couldn\'t load your profile information. Please try again later.',
    backToDashboard: 'Back to Dashboard',
    userProfile : 'User Profile',
    manageAccountInfo: 'Manage Account Information and security',
    changePass : 'Change Password',
    editProfile : 'Edit Profile',
    updating : 'Updating...',
    updatePass : 'Update Password',
    saving : 'Saving...',
    saveChanges : 'Save Changes',
    currentPass : 'Current Password',
    currentPassPlaceholder : 'Enter your current password',
    newPass : 'New Password',
    newPassPlaceholder : 'Enter your new password',
    confirmPass : 'Confirm New Password',
    confirmPassPlaceholder : 'Confirm your new password',
    newPassHint : "Password must be at least 6 characters long",
    passUpdatedSucc : 'Password updated successfully !',
    personalInformation: "Personal Information",
    fullName: "Full Name",
    emailAddress: "Email Address",
    notProvided: "Not provided",
    locationInformation: "Location Information",
    city: "City",
    enterYourCity: "Enter your city",
    accountSecurity: "Account Security",
    changePassword: "Change Password",
    recentActivity: "Recent Activity",
    daysAgo: "days ago",
    lastLogin: "Last login",
    accountCreated: "Account created",
    profileLastUpdated: "Profile last updated",
    todayAt: "Today at",
    na: "N/A",
    pleaseLogInToManageFavourite: "Please log in to manage your favourites",
    areYouSureYouWantToLogout: "Are you sure you want to logout?",
     loadingProfile: "Loading your profile...",
       // Error/Login state
    welcome: "Welcome to Your Account",
    signInMessage: "Sign in to access your personalized dashboard and manage your preferences.",
    signIn: "Sign In to Your Account",
    createAccount: "Create New Account",
    valuedCustomer: "Valued Customer",
       profile: "Profile",
    orders: "Orders",
    favorites: "Favorites",
    settings: "Settings",
       // Favorites section
    yourFavorites: "Your Favorites",
    favoritesEmpty: "Your Favorites is empty",
    startAddingItems: "Start adding items you love!",
    change : 'Change',
       accountActions: "Account Actions",
    manageSession: "Manage your account session",
    signOut: "Sign Out",
    signOutWarning: "Once you log out, you'll need to sign in again to access your account.",
    freeDeliveryMsg : 'Free delivery on orders over 500 MAD • Premium quality guaranteed',
    pleaseLog : 'Please log in to access this section.',

     // Loading state
    loadingProducts: "Loading featured products...",
    
    // Premium badge
    premiumProducts: "Premium Parapharmacy Products",
    
    // Hero text
    wellnessJourney: "Your Wellness Journey",
    startsHere: "Starts Here",
    
    // Product badges
    sale: "Sale",
    new: "New",
    trending: "Trending",
    
    // Floating elements
    freeDelivery: "Free delivery",
    fromAmount: "From 500 MAD",
    quality: "Quality",
    guaranteed: "Guaranteed",
     // Loading state
    loadingFavorites: "Loading your favorites...",
    
    // Error state
    errorLoading: "Error Loading Favorites",
    errorMessage: "There was a problem loading your favorite items. Please try again.",
    tryAgain: "Try Again",
    
    // Empty state
    backToShopping: "Back to Shopping",
    favoritesEmpty: "Your Favorites is Empty",
    emptyMessage: "You haven't added any products to your favorites yet. Start exploring our collection and add items you love!",
    exploreProducts: "Explore Products",
      myFavorites: "My Favorites",
    itemsSaved: "items saved for later",
    item: "item",
    items: "items",
    refresh: "Refresh",
    
    // Item badges
    pack: "Pack",

    off: "off",

       // Action buttons
    viewDetails: "View Details",
    decreaseQuantity: "Decrease quantity",
    increaseQuantity: "Increase quantity",
    addToCart: "Add to Cart",
    add: "Add",
    
    // Summary section
    favoritesSummary: "Favorites Summary",
    totalValue: "Total Value",
    continueShopping: "Continue Shopping",
    youHave : 'You have',
    inYourFavorites: 'in your favorites',

    // Categories
    uncategorized: "Uncategorized",
     orderHistory: "Order History",
    
    // Error state
    failedToLoad: "Failed to load orders",
    tryAgain: "Try Again",
    
    // Header
    refresh: "Refresh",
    
    // Order status
   
    pending: "Pending",
    confirmed: "Confirmed",
    processing: "Processing",
    shipped: "Shipped",
    delivered: "Delivered",
    cancelled: "Cancelled",
    
    
    // Order details
    viewDetails: "View Details",
    hideDetails: "Hide Details",
    orderItems: "Order Items",
    items: "items",
    orderSummary: "Order Summary",
    subtotal: "Subtotal",
    shipping: "Shipping",
    total: "Total",
    
    // Customer information
    customerInformation: "Customer Information",
    customer: "Customer",
    phoneNumber: "Phone Number",
    
    // Shipping information
    shippingAddress: "Shipping Address",
    deliveryArea: "Delivery Area",
    
    // Empty state
    noOrders: "No orders yet",
    emptyMessage: "Your order history will appear here",
    startShopping: "Start Shopping",
    each : 'each',


     cartnameRequired: "Name is required",
     cartnameMinLength: "Name must be at least 2 characters",
     cartphoneRequired: "Phone number is required",
     cartphoneInvalid: "Please enter a valid Moroccan phone number",
     cartcityRequired: "City is required",
     cartaddressRequired: "Address is required",
     cartdeliveryAreaRequired: "Please select a delivery area",
       yourCartIsEmpty: "Your cart is empty",
    emptyCartMessage: "Looks like you haven't added any products to your cart yet.",
    startShopping: "Start Shopping",
    
      stepcart: "Shopping Cart",
      stepinfo: "Customer Info",
      stepreview: "Order Review",
        // Cart step
       yourCartItems: "Your Cart Items",
    pack: "Pack",
    product: "Product",
    cartcustomerInformation: "Customer Information",
    cartfullName: "Full Name",
    cartenterFullName: "Enter your full name",
    cartphoneNumber: "Phone Number",
    cartenterPhoneNumber: "e.g., 0612345678",
    cartcity: "City",
    cartenterCity: "Enter your city",
    cartdeliveryArea: "Delivery Area",
    cartselectDeliveryArea: "Select delivery area",
    cartaddress: "Address",
    cartenterAddress: "Enter your complete address",
      // Review step
    cartorderReview: "Order Review",
    cartorderItems: "Order Items",
    cartquantity: "Qty",
    
    // Order summary
    cartorderSummary: "Order Summary",
    cartsubtotal: "Subtotal",
    cartdeliveryFee: "Delivery Fee",
    cartdeliveryDiscount: "Delivery Discount",
    carttotal: "Total",
    
    // Free delivery messages
    cartcongratulations: "Congratulations!",
    cartfreeDelivery: "FREE delivery",
    cartfreeDeliveryMessage: "You've qualified for FREE delivery on orders over 500 DH.",
    cartaddMoreForFreeDelivery: "Add {amount} DH more to get FREE delivery!",
    continueToInformation: "Continue to Information",
    reviewOrder: "Review Order",
    backToCart: "Back to Cart",
    completeOrder: "Complete Order",
    backToInformation: "Back to Information",
    moreToget: 'more to get',
    youVe : 'You\'ve qualified for',
    onOrdersOver : 'on orders over',
    free : 'Free',
    packContent : 'Pack Content',
    'quantity' : 'Quantity',
    buyNow : 'Buy Now',
    allProducts : 'All products',
    packages : 'Packages',
    specialOffers : 'Special Offers',
    featured: "Featured",
      "price-low-high": "Price: Low to High",
      "price-high-low": "Price: High to Low",
      "name-a-z": "Name: A to Z",
      "name-z-a": "Name: Z to A",
      'clearAllFilters' : 'Clear All Filters',
      'priceRange' : 'Price Range',
      minPrince : 'Min Price',
      maxPrice : 'Max Price',
      'Premium-Wellness-Partner' : 'Premium Wellness Partner',
      'yourTrust' : ' Your trusted partner for premium wellness products and healthcare solutions.',
      getInTouch : 'Get In Touch',
      socialMedia: 'Social Medial',
      allRightsReserved : 'All Rights Reserved',
      madeBy : 'Made By',
      home : 'Home',
      cart : 'Cart',
      save : 'Save',
      visitUs : 'Visit Us',
      comeVisitUs : 'Come visit  our location or contact us using your preferred method',
      weAreHere : 'We are here ',
      hoursOfWork : 'Hours of Work',
      hoursOfWork2 : 'Everyday: 10 AM - 11 PM',
      getDirection : 'Get Directions',
      callNow : 'Call Now',
      ourLocation : 'Our Location',

      pageNotFound: "Page Not Found",
      goBackHome: "Go Back Home",
      errorMsg : ' Sorry, the page you are looking for doesn\'t exist or has been moved.',
      orderSuccess : 'Your order has been placed successfully!',
      noOrdersYet : 'No orders found yet.',
      orderHistoryWillAppear : 'Your order history will appear here once you have placed an order.',
      viewDetails : 'View Details',
      hideDetails : 'Hide Details',
      memberSince : 'Member Since',
      'Update your account password' : 'Update your account password',
      'deleteProductAlertMsg' : "⚠  If you delete a product and it exists in a pack, it will also be removed from it!",
       'manageYourBrands' : 'Manage your brands ',
       'deleteBrandMsg' : '"⚠ If you delete a brand, all associated products will also be removed!',
          'Product is out of stock' : 'Product is out of stock',
          'unread' : 'unread',
          'read' : 'read',
          'all':'all',
          'Notifications': 'Notifications',
          'New order received': 'New order received',
          'Product is low on stock': 'Product is low on stock',
          'General Notification': 'General Notification',
          'new order' : 'New Order',
          'low stock' : 'Low Stock',
          'out of stock' : 'Out Of Stock',
          'A new order has been placed by':'A new order has been placed by',
          'The product':'The product',
          'is out of stock.':'is out of stock.',
          'is low on stock.':'is low on stock.',
          'No notifications':'No notifications',
          'You\'re all caught up! No notifications to display.': 'You\'re all caught up! No notifications to display.'

  },
  fr: {
    'You\'re all caught up! No notifications to display.': 'Vous avez tout vu ! Aucune notification à afficher.',
    'No notifications': 'Aucune notification',
    'is out of stock.': 'est en rupture de stock.',
    'is low on stock.': 'est en faible stock.',
    'The product': 'Le produit',
    'A new order has been placed by': 'Une nouvelle commande a été passée par',
    'new order': 'Nouvelle Commande',
    'low stock': 'Faible Stock',
    'out of stock': 'Rupture de Stock',
    'Product is low on stock': 'Le produit est en rupture de stock',
    'General Notification': 'Notification Générale',
    'Notifications': 'Notifications',
    'New order received': 'Nouvelle commande reçue',
    'all':'tous',
    'unread' : 'non lu',
    'read' : 'lu',
    'Product is out of stock' : 'Le produit est en rupture de stock',
    deleteBrandMsg: '"⚠ Si vous supprimez une marque, tous les produits associés seront également supprimés!',
    manageYourBrands : 'Gérer vos marques',
    'deleteProductAlertMsg' : "Si vous supprimez un produit et qu'il existe dans un pack, il sera également supprimé de celui-ci!",
    'Update your account password' : 'Mettre à jour votre mot de passe',
    memberSince : 'Membre Depuis',
    viewDetails : 'Voir les Détails',
    hideDetails : 'Masquer les Détails',
    orderHistoryWillAppear : 'Votre historique de commandes apparaîtra ici une fois que vous aurez passé une commande.',
    noOrdersYet : 'Aucune commande trouvée pour le moment.',
    orderSuccess : 'Votre commande a été passée avec succès!',
    pageNotFound: "Page Non Trouvée",
    goBackHome: "Retourner à l'Accueil",
    errorMsg: "Désolé, la page que vous recherchez n'existe pas ou a été déplacée.",
    ourLocation: 'Notre Emplacement',

    callNow : 'Appeler Maintenant',
    getDirection : 'Obtenir des Directions',
    hoursOfWork2 : 'Tous les jours: 10h - 23h',
    hoursOfWork : 'Heures de Travail',
    weAreHere : 'Nous sommes ici',
    comeVisitUs : 'Venez visiter notre site web ou contactez-nous en utilisant votre méthode préférée',
    visitUs : 'Visitez Nous',
    save : 'Enregistrer',
    cart : 'Panier',
    home : 'Accueil',

    "getInTouch": "Nous Contacter",
    "socialMedia": "Médias Sociaux",
    "allRightsReserved": "Tous les Droits Réservés",
    "madeBy": "Fabriqué Par",
    "yourTrust": "Votre partenaire de confiance pour des produits de bien-être premium et des solutions de santé.",
    "Premium-Wellness-Partner": "Partenaire de Bien-Être Premium",
    minPrice: "Prix Min",
    maxPrice: "Prix Max",
    priceRange: "Gamme de Prix",
    clearAllFilters: "Effacer tous les filtres",
       featured: "En vedette",
      "price-low-high": "Prix: Croissant",
      "price-high-low": "Prix: Décroissant",
      "name-a-z": "Nom: A à Z",
      "name-z-a": "Nom: Z à A",
    searchProducts : 'Rechercher des produits...',
    allProducts : 'Tous les produits',
    packages : 'Paquets',
    specialOffers : 'Offres Spéciales',
    buyNow : 'Acheter Maintenant',
    quantity : 'Quantité',

    packContent: "Contenu du Pack",
    productDetails: "Détails du Produit",
    onOrdersOver : 'pour les commandes supérieures à',
    youVe : 'Vous avez droit à',
    free : 'Gratuit',
    moreToget: 'plus à obtenir',
      continueToInformation: "Continuer vers les Informations",
    reviewOrder: "Revoir la Commande",
    backToCart: "Retour au Panier",
    completeOrder: "Finaliser la Commande",
    backToInformation: "Retour aux Informations",
    // Review step
    cartorderReview: "Revue de Commande",
    cartorderItems: "Articles de Commande",
    cartquantity: "Qté",
    
    // Order summary
    cartorderSummary: "Résumé de la Commande",
    cartsubtotal: "Sous-total",
    cartdeliveryFee: "Frais de Livraison",
    cartdeliveryDiscount: "Remise Livraison",
    carttotal: "Total",
    
    // Free delivery messages
    cartcongratulations: "Félicitations!",
    cartfreeDelivery: "Livraison GRATUITE",
    cartfreeDeliveryMessage: "Vous avez droit à la livraison GRATUITE pour les commandes supérieures à 500 DH.",
    cartaddMoreForFreeDelivery: "Ajoutez {amount} DH de plus pour obtenir la livraison GRATUITE!",
    cartcustomerInformation: "Informations Client",

    cartfullName: "Nom Complet",
    cartenterFullName: "Entrez votre nom complet",
    cartphoneNumber: "Numéro de Téléphone",
    cartenterPhoneNumber: "ex., 0612345678",
    cartcity: "Ville",
    cartenterCity: "Entrez votre ville",
    cartdeliveryArea: "Zone de Livraison",
    cartselectDeliveryArea: "Sélectionnez une zone de livraison",
    cartaddress: "Adresse",
    cartenterAddress: "Entrez votre adresse complète",
      // Cart step
    yourCartItems: "Vos Articles du Panier",
    pack: "Pack",
    product: "Produit",
    
      stepcart: "Panier d'Achat",
      stepinfo: "Informations Client",
      stepreview: "Revue de Commande",
     yourCartIsEmpty: "Votre panier est vide",
    emptyCartMessage: "Il semble que vous n'ayez encore ajouté aucun produit à votre panier.",
    startShopping: "Commencer à Magasiner",
     cartnameRequired: "Le nom est requis",
      cartnameMinLength: "Le nom doit comporter au moins 2 caractères",
      cartphoneRequired: "Le numéro de téléphone est requis",
      cartphoneInvalid: "Veuillez entrer un numéro de téléphone marocain valide",
      cartcityRequired: "La ville est requise",
      cartaddressRequired: "L'adresse est requise",
      cartdeliveryAreaRequired: "Veuillez sélectionner une zone de livraison",
      // Loading state
    orderHistory: "Historique des Commandes",
    
    // Error state
    failedToLoad: "Échec du chargement des commandes",
    tryAgain: "Réessayer",
    
    // Header
    refresh: "Actualiser",
    each :'chaque',
    
    // Order status
    
      pending: "En attente",
      confirmed: "Confirmé",
      processing: "En traitement",
      shipped: "Expédié",
      delivered: "Livré",
      cancelled: "Annulé",
    
    
    // Order details
    viewDetails: "Voir les Détails",
    hideDetails: "Masquer les Détails",
    orderItems: "Articles de Commande",
    items: "articles",
    orderSummary: "Résumé de la Commande",
    subtotal: "Sous-total",
    shipping: "Livraison",
    total: "Total",
    
    // Customer information
    customerInformation: "Informations Client",
    customer: "Client",
    phoneNumber: "Numéro de Téléphone",
    
    // Shipping information
    shippingAddress: "Adresse de Livraison",
    deliveryArea: "Zone de Livraison",
    
    // Empty state
    noOrders: "Aucune commande pour le moment",
    emptyMessage: "Votre historique de commandes apparaîtra ici",
    startShopping: "Commencer à Magasiner",
    youHave: "Vous avez",
    inYourFavorites: "dans vos favoris",

    // Action buttons
    viewDetails: "Voir les Détails",
    decreaseQuantity: "Diminuer la quantité",
    increaseQuantity: "Augmenter la quantité",
    addToCart: "Ajouter au Panier",
    add: "Ajouter",
    
    // Summary section
    favoritesSummary: "Résumé des Favoris",
    totalValue: "Valeur Totale",
    continueShopping: "Continuer les Achats",
    
    // Categories
    uncategorized: "Non catégorisé",
     loadingFavorites: "Chargement de vos favoris...",
    
    // Error state
    errorLoading: "Erreur de Chargement des Favoris",
    errorMessage: "Un problème est survenu lors du chargement de vos articles favoris. Veuillez réessayer.",
    tryAgain: "Réessayer",
    
    // Empty state
    backToShopping: "Retour aux Achats",
    favoritesEmpty: "Vos Favoris sont Vides",
    emptyMessage: "Vous n'avez encore ajouté aucun produit à vos favoris. Explorez notre collection et ajoutez les articles que vous aimez !",
    exploreProducts: "Explorer les Produits",
    // Header
    myFavorites: "Mes Favoris",
    itemsSaved: "articles enregistrés pour plus tard",
    item: "article",
    items: "articles",
    refresh: "Actualiser",
    
    // Item badges
    pack: "Pack",
   
    off: "de réduction",
    
        // Loading state
    loadingProducts: "Chargement des produits en vedette...",
    
    // Premium badge
    premiumProducts: "Produits de Parapharmacie Premium",
    
    // Hero text
    wellnessJourney: "Votre Parcours Bien-être",
    startsHere: "Commence Ici",
    
    // Product badges
    sale: "Soldes",
    new: "Nouveau",
    trending: "Tendance",
    
    // Floating elements
    freeDelivery: "Livraison gratuite",
    fromAmount: "À partir de 500 MAD",
    quality: "Qualité",
    guaranteed: "Garantie",

    pleaseLog : 'Veuillez vous connecter pour accéder à cette section.',
    freeDeliveryMsg : 'Livraison gratuite sur les commandes de plus de 500 MAD • Qualité premium garantie',
    accountActions: "Actions du Compte",
    manageSession: "Gérer votre session de compte",
    signOut: "Se Déconnecter",
    signOutWarning: "Une fois déconnecté, vous devrez vous reconnecter pour accéder à votre compte.",
    change : 'Changer',
    yourFavorites: "Vos Favoris",
    favoritesEmpty: "Vos Favoris sont vides",
    startAddingItems: "Commencez à ajouter des articles que vous aimez !",
       profile: "Profil",
    orders: "Commandes",
    favorites: "Favoris",
    settings: "Paramètres",
    valuedCustomer: "Client Privilégié",
    welcome: "Bienvenue sur Votre Compte",
    signInMessage: "Connectez-vous pour accéder à votre tableau de bord personnalisé et gérer vos préférences.",
    signIn: "Se connecter à votre compte",
    createAccount: "Créer un nouveau compte",
    loadingProfile: "Chargement de votre profil...",
    areYouSureYouWantToLogout: "Êtes-vous sûr de vouloir vous déconnecter ?",
    pleaseLogInToManageFavourite: "Veuillez vous connecter pour gérer vos favoris",
    daysAgo: "il y a quelques jours",
    personalInformation: "Informations Personnelles",
    fullName: "Nom Complet",
    emailAddress: "Adresse Email",
    notProvided: "Non fourni",
    locationInformation: "Informations de Localisation",
    city: "Ville",
    enterYourCity: "Entrez votre ville",
    accountSecurity: "Sécurité du Compte",
    changePassword: "Changer le Mot de Passe",
    recentActivity: "Activité Récente",
    lastLogin: "Dernière connexion",
    accountCreated: "Compte créé",
    profileLastUpdated: "Profil dernièrement mis à jour",
    todayAt: "Aujourd'hui à",
    na: "Non Disponible",
    passUpdatedSucc : 'Mot de passe mis à jour avec succès !',
    newPassHint : "Le mot de passe doit comporter au moins 6 caractères",
    newPass : 'Nouveau Mot de Passe',
    newPassPlaceholder : 'Entrez votre nouveau mot de passe',
    confirmPass : 'Confirmer le Nouveau Mot de Passe',
    confirmPassPlaceholder : 'Confirmez votre nouveau mot de passe',
    currentPass : 'Mot de Passe Actuel',
    currentPassPlaceholder : 'Entrez votre mot de passe actuel',
    updating : 'Mise à jour...',
    updatePass : 'Mettre à jour le mot de passe',
    saving : 'Enregistrement...',
    saveChanges : 'Enregistrer les modifications',
    changePass : 'Changer le Mot de Passe',
    editProfile : 'Modifier le Profil',
    userProfile : 'Profil de l\'Utilisateur',
    manageAccountInfo : 'Gérer les Informations et la Sécurité du Compte',
    backToDashboard: 'Retour au tableau de bord',
    profileNotFound: 'Profil non trouvé',
    profileNotFoundDesc: 'Nous n\'avons pas pu charger les informations de votre profil. Veuillez réessayer plus tard.',
    currentPassReq: 'Le mot de passe actuel est requis',
    newPassReq: 'Le nouveau mot de passe est requis',
    newPassMin: 'Le nouveau mot de passe doit comporter au moins 6 caractères',
    newPassConfirm: 'Veuillez confirmer votre nouveau mot de passe',
    newPassMismatch: 'Les mots de passe ne correspondent pas',
    managementDashboard: 'Tableau de Bord de Gestion',
    cusSearchPlaceholder : 'Rechercher des clients par nom, email, téléphone ou emplacement...',
    registeredCUs : 'Clients Enregistrés',
    cusDirectory: 'Répertoire des Clients',
    allregCus : 'Tous les Clients Enregistrés',
    cus : 'Client',
    contact : 'Contact',
    orders : 'Commandes',

    totalSpent : 'Total Dépensé',
    joined : 'Rejoint',
    noCustomersFound: 'Aucun client trouvé',
    cusDetails : 'Détails du Client',
    personalInfo: 'Informations Personnelles',
    customerSince: 'Client Depuis',
    orderInfo : 'Informations sur la Commande',
    totalOrders: 'Total des Commandes',
    averageSpent: 'Dépenses Moyennes',
    lastOrder: 'Dernière Commande',
    sendMail: 'Envoyer un Email',










    // Navigation
    dashboard: 'Tableau de Bord',
    products: 'Produits',
    orders: 'Commandes',
    customers: 'Clients',
    reports: 'Rapports',
    settings: 'Paramètres',
    companies: 'Marques',
    categories: 'Catégories',
    packs: 'Packs',

    // Dashboard
    totalRevenue: 'Chiffre d\'Affaires Total',
    "Orders & Deliveries" : 'Commandes & Livraisons',
    "Today's Revenue": "Chiffre d'Affaires du Jour",
    'Stock Alerts': 'Alertes de Stock',
    totalProducts: 'Total Produits',
    'Total / Delivered': 'Total / Livrées',
    'Low / Out of Stock':'Faible / Rupture de Stock',
    Stock: 'Stock',
    lowStock: 'Stock Faible',
    expiringProducts: 'Expire Bientôt',
    recentSales: 'Ventes Récentes',
    topProducts: 'Meilleurs Produits',
    inventoryValue: 'Valeur Inventaire',
    monthlyGrowth: 'Croissance Mensuelle',
    dashboardTitle: 'Tableau de Bord',
    dashboardWelcome: 'Bienvenue ! Voici un aperçu de vos ventes.',
    lastUpdated: 'Dernière mise à jour',
    refreshData: 'Rafraîchir',
    bestPerformingItems: 'Meilleurs produits par chiffre d\'affaires',
    topSellingProducts: 'Produits les Plus Vendus',
    viewAll: 'Voir Tout',
    unknownProduct: 'Produit Inconnu',
    unitsSold: 'unités vendues',
    each: 'chacun',
    categorySales: 'Ventes par Catégorie',
    revenueByProductCategory: 'Chiffre d\'affaires par catégories',
    all: 'Tout',
    today: 'Aujourd\'hui',
    month: 'Mois',
    year: 'Année',
    ofTotalRevenue: 'du chiffre d\'affaires total',
    noSalesData: 'Aucune donnée de vente disponible',
    salesWillAppearHere: 'Les ventes apparaîtront ici',
    noCategorySales: 'Aucune vente par catégorie',
    salesWillAppear: 'Les ventes apparaîtront ici',
    orderStatusSummary: 'Résumé du Statut des Commandes',
    overviewOrders: 'Aperçu de toutes les commandes',
    pendingOrders: 'Commandes en attente',
    deliveredOrders: 'Commandes livrées',
    returnedOrders: 'Commandes retournées',
    canceledOrders: 'Commandes annulées',
    pendingOrdersDesc: 'Commandes en attente de traitement',
    deliveredOrdersDesc: 'Commandes livrées avec succès',
    returnedOrdersDesc: 'Commandes retournées',
    canceledOrdersDesc: 'Commandes annulées',
    
    // Products
    'Total Products': 'Total Produits',
    Product: 'Produit',
    Category: 'Catégorie',
    price: 'Prix',
    'Current Stock': 'Stock Actuel',
    Offer: 'Offre',
    Status: 'Statut',
    addProduct: 'Ajouter Produit',
    editProduct:'Modifier un Produit',
    Actions: 'Actions',
    deleteProduct: 'Supprimer Produit',
    searchProductsByName: 'Rechercher un produit par nom.',
    'Low Stock': 'Stock Faible',
    'Out Of Stock': 'Rupture de Stock',
    'All Categories': 'Toutes les Catégories',
    Refresh: 'Rafraîchir',
    'Product Management': 'Gestion des Produits',
    'Monitor and manage your products': 'Surveillez et gérez vos produits',
    "Create Offer for": "Créer une offre pour",
    "Regular Price": "Prix régulier",
    "Offer Price": "Prix de l'offre",
    "Enter offer price": "Entrez le prix de l'offre",
    "Start Date": "Date de début",
    "End Date": "Date de fin",
    "Cancel": "Annuler",
    "Create Offer": "Créer l'offre",
    "Creating...": "Création...",
    currency: "MAD",
    productName:'Nom du Produit',
    enterProductName: 'Entrez le nom du produit',
    selectCategory: 'Sélectionnez la catégorie',
    selectCompany: 'Sélectionnez la société',
    productImage: 'Image du produit',
    uploadImage: "Télécharger l'image",
    supportedFormats: "Formats supportés : JPG, PNG, GIF. Taille max : 5 Mo",
    description: 'Description',
    enterProductDescription: 'Entrez la description du produit',
    updateProductInfo: 'Mettre à jour les informations du produit',
    addNewProduct: 'Ajouter un nouveau produit',
    somethingWentWrong: 'Une erreur est survenue. Veuillez réessayer.',
    networkError: 'Erreur réseau. Veuillez vérifier votre connexion et réessayer.',
    selectImageFile: 'Veuillez sélectionner un fichier image',
    imageSizeLimit: "La taille de l'image doit être inférieure à 5 Mo",

    // Packs
    "Pack Management": "Gestion des packs",
    "Create and manage product packs": "Créer et gérer des packs de produits",
    "New Pack": "Nouveau pack",
    "Search packs by name...": "Rechercher des packs par nom...",
    "Pack Name": "Nom du pack",
    "No description": "Aucune description",
    "No packs found": "Aucun pack trouvé",
    "Create your first pack to get started": "Créez votre premier pack pour commencer",
    "packDetails": "Détails du Pack",
    "noDescription": "Aucune description",
    "productsInPack": "Produits dans ce pack",
    "noProductsInPack": "Aucun produit dans ce pack",
    "packSummary": "Résumé du Pack",
    "packPrice": "Prix du Pack",
    "created": "Créé le",
    "lastUpdated": "Dernière mise à jour",
    "close": "Fermer",
    "create pack": "Créer nouveau pack",

    nameRequired: "Le nom du pack est requis",
  nameMin: "Le nom du pack doit contenir au moins 2 caractères",
  nameMax: "Le nom du pack ne peut pas dépasser 100 caractères",

  descriptionRequired: "La description est requise",
  descriptionMax: "La description ne peut pas dépasser 500 caractères",

  priceRequired: "Le prix est requis",
  priceInvalid: "Le prix doit être un nombre positif",
  priceMax: "Le prix ne peut pas dépasser 10 000",

  productRequired: "Veuillez sélectionner au moins un produit",
  somethingWentWrong: 'Une erreur est survenue. Veuillez réessayer.',
  networkError: 'Erreur réseau. Veuillez vérifier votre connexion et réessayer.',

    comTitle: "Gestion des Marques",
    comAddButton: "Ajouter une Maque",
    comTotalCompanies: "Total des marques",
    comSearchPlaceholder: "Rechercher des marques...",
    comName: "Nom",
    comCreatedAt: "Créé le",
    comActions: "Actions",
    comEdit: "Modifier",
    comDelete: "Supprimer",
    comNoCompaniesFound: "Aucune marque trouvée",
    comTryAdjustingSearch: "Essayez d'ajuster vos critères de recherche",
     comAddTitle: "Ajouter une nouvelle marque",
    comAddDesc: "Créer une nouvelle marque",
    comEditTitle: "Modifier la marque",
    comEditDesc: "Mettre à jour les informations de la marque",
    comNameLabel: "Nom de la marque",
    comNamePlaceholder: "Entrez le nom de la marque",
    comNameRequired: "Le nom de la marque est requis",
    comNameMinLength: "Le nom de la marque doit comporter au moins 2 caractères",
    comCreateButton: "Créer la marque",
    comUpdateButton: "Mettre à jour la marque",
    comCreating: "Création...",
    comUpdating: "Mise à jour...",


    // Categories
    skincare: 'Soins de la Peau',
    haircare: 'Soins Capillaires',
    supplements: 'Compléments',
    babycare: 'Bébé & Maternité',
    hygiene: 'Hygiène Personnelle',
    herbal: 'Remèdes à Base de Plantes',
    cosmetics: 'Cosmétiques',
    medical: 'Dispositifs Médicaux',
    allTime: 'Tout le Temps',
    today: 'Aujourd\'hui',
    week: 'Cette Semaine',
    month: 'Ce Mois',
    adminPanel: 'Panneau Administratif',

     "loadingCategories": "Chargement des catégories...",
  "errorLoadingCategories": "Erreur lors du chargement des catégories.",
  "categories": "Catégories",
  "manageCategories": "Gérez et organisez vos catégories de produits",
  "refresh": "Rafraîchir",
  "addCategory": "Ajouter une catégorie",
  "searchCategoriesPlaceholder": "Rechercher des catégories par nom...",
  "categoryList": "Liste des catégories",
  "name": "Nom",
  "actions": "Actions",
  "edit": "Modifier",
  "delete": "Supprimer",
  "noCategoriesFound": "Aucune catégorie trouvée",
  "tryAdjustingSearch": "Essayez de modifier votre recherche",
  "showing": "Affichage de",
  "to": "à",
  "of": "sur",
  "page": "Page",
  "previous": "Précédent",
  "next": "Suivant",
    
    // Orders
    'Orders Management': 'Gestion des Commandes',
    'Manage and track all customer orders': 'Gérer et suivre toutes les commandes des clients',
    'Total Orders': 'Total des Commandes',
    'Pending Orders': 'Commandes en Attente',
    'Delivered Orders': 'Commandes Livrées',
    'Returned Orders': 'Commandes Retournées',
    'Cancelled Orders': 'Commandes Annulées',
    'Order Number': 'Numéro de Commande',
    'Customer': 'Client',
    'Customer Name': 'Nom du Client',
    'Items': 'Articles',
    'Total': 'Total',
    'Order Status': 'Statut de Commande',
    'Order Date': 'Date de Commande',
    'No orders found': 'Aucune commande trouvée',
    'Search orders by order number, name, or phone...': 'Rechercher des commandes par numéro, nom ou téléphone...',
    'All Statuses': 'Tous les Statuts',
    'All Dates': 'Toutes les Dates',
    'This Week': 'Cette Semaine',
    'This Month': 'Ce Mois',
    'Previous': 'Précédent',
    'Next': 'Suivant',
    'Showing': 'Affichage',
    'per page': 'par page',
    'vs last month': 'par rapport au mois dernier',
    'Customer Information': 'Informations Client',
    'Order Information': 'Informations sur la Commande',
    'Total Amount': 'Montant Total',
    'Order Items': 'Articles de la Commande',
    'Quantity': 'Quantité',

     catEditTitle: "Modifier la catégorie",
    catAddTitle: "Ajouter une nouvelle catégorie",
    catEditSubtitle: "Mettre à jour les informations de la catégorie",
    catAddSubtitle: "Créer une nouvelle catégorie de produit",
    catNameLabel: "Nom de la catégorie",
    catNamePlaceholder: "Saisissez le nom de la catégorie",
    catUpdating: "Mise à jour...",
    catCreating: "Création...",
    catUpdateButton: "Mettre à jour la catégorie",
    catCreateButton: "Créer la catégorie",

    // Companies
    Company : 'Entreprise',

     editPack: "Modifier le pack",
  createPack: "Créer un pack",
  page: "Page",
  of: "sur",
  searchProductsByName: "Rechercher des produits par nom",
  previous: "Précédent",
  next: "Suivant",
  showing: "Affichage de",
  to: "à",
  products: "produits",
  packDetails: "Détails du pack",
  packName: "Nom du pack",
  description: "Description",
  characters: "caractères",
  price: "Prix",
  selectedProducts: "Produits sélectionnés",
  noProductsSelected: "Aucun produit sélectionné",
  cancel: "Annuler",
  updating: "Mise à jour...",
  creating: "Création...",
  updatePack: "Mettre à jour le pack",
  createPackBtn: "Créer un pack",
  stock: "Stock",


    catNameRequired: "Le nom de la catégorie est requis",
    catNameMin: "Le nom de la catégorie doit contenir au moins 2 caractères",

    // Common
    save: 'Enregistrer',
    cancel: 'Annuler',
    delete: 'Supprimer',
    edit: 'Modifier',
    view: 'Voir',
    add: 'Ajouter',
    search: 'Rechercher',
    filter: 'Filtrer'
  },
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const language = useSelector((state) => state.ui.language);
  const dispatch = useDispatch();

  const setLanguage = (lang) => {
    dispatch(setLanguageAction(lang));
  };

  const t = (key) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      <div dir="ltr" className="font-inter">
        {children}
      </div>
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};